version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    auto-merge: true
    auto-commit-message: "chore(deps): bump github action dependencies"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    groups:
      actions-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
